version: "3.5"
services:
  python-script:
    container_name: python-script
    build: ./
    image: stlavrdocker/iroha-metrics:latest
    working_dir: /app
    volumes:
      - ./reader:/app
    environment:
    - "HOSTNAME=s1.tst.iroha.tech:8080,s2.tst.iroha.tech:8080,s3.tst.iroha.tech:8080,s4.tst.iroha.tech:8080"
    networks:
      - iroha-net
      - traefik-net

networks:
  iroha-net:
    external:
      name: iroha-net
  traefik-net:
    external:
      name: traefik-net